version: '3.8'

services:
  api4mongodb:
    build: .
    ports:
      - "8001:8001"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB=productdb
      - SECRET_KEY=your-secret-key-for-jwt
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=10
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - app-network

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
